import React, {useRef, useState} from 'react';
import styles from './styles.module.css';

const KLEE_SCRIPT_SRC = 'https://joined-forces.github.io/klee/js/klee.min.js';
const KLEE_SCRIPT_ID = 'pla4y-klee-script';

declare global {
  interface Window {
    Klee?: {
      init?: (canvas: HTMLCanvasElement) => {display?: (blueprintText: string) => void};
      get?: (canvas: HTMLCanvasElement) => {display?: (blueprintText: string) => void} | undefined;
    };
  }
}

const exampleBlueprint = `Begin Object Class=/Script/BlueprintGraph.K2Node_Event Name="K2Node_Event_0"
    EventReference=(MemberParent=Class'"/Script/Engine.Actor"',MemberName="ReceiveBeginPlay")
    bOverrideFunction=True
    bCommentBubblePinned=True
    NodeGuid=DA78E90542B5EA6FFF2BB580420BADA4
    CustomProperties Pin (PinId=72D40BCB43A58F1C676E9AA9770D2D80,PinName="OutputDelegate",Direction="EGPD_Output",PinType.PinCategory="delegate",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(MemberParent=Class'"/Script/Engine.Actor"',MemberName="ReceiveBeginPlay"),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=True,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
    CustomProperties Pin (PinId=43C25E4A4F36B0A3D974C58D187B99D0,PinName="then",Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=True,LinkedTo=(K2Node_CallFunction_8 347E2B8849A88B5B6EB338B0CF412295,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="K2Node_CallFunction_8"
    FunctionReference=(MemberParent=Class'"/Script/Engine.KismetSystemLibrary"',MemberName="PrintString")
    NodePosX=288
    AdvancedPinDisplay=Hidden
    EnabledState=DevelopmentOnly
    NodeGuid=D94D72E348471465CF685AB3C289A168
    CustomProperties Pin (PinId=347E2B8849A88B5B6EB338B0CF412295,PinName="execute",PinToolTip="\\nExec",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,LinkedTo=(K2Node_Event_0 43C25E4A4F36B0A3D974C58D187B99D0,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
    CustomProperties Pin (PinId=867BBF3A41E77FED7EBB01B783D1BD58,PinName="then",PinToolTip="\\nExec",Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
    CustomProperties Pin (PinId=89FC8C6B4DB2E65B8FFC6CB80DC5386D,PinName="self",PinFriendlyName=NSLOCTEXT("K2Node", "Target", "Target"),PinToolTip="Target\\nKismet System Library Object Reference",PinType.PinCategory="object",PinType.PinSubCategory="",PinType.PinSubCategoryObject=Class'"/Script/Engine.KismetSystemLibrary"',PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,DefaultObject="/Script/Engine.Default__KismetSystemLibrary",PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
    CustomProperties Pin (PinId=B74444DF4AA54A124612178F2F98CE1F,PinName="InString",PinToolTip="In String\\nString\\n\\nThe string to log out",PinType.PinCategory="string",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,DefaultValue="Let's share Blueprints!",AutogeneratedDefaultValue="Hello",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object`;

function loadKleeScript(): Promise<void> {
  if (typeof window === 'undefined') {
    return Promise.resolve();
  }

  if (window.Klee) {
    return Promise.resolve();
  }

  const existingScript = document.getElementById(KLEE_SCRIPT_ID) as HTMLScriptElement | null;

  if (existingScript) {
    return new Promise((resolve, reject) => {
      if (window.Klee) {
        resolve();
        return;
      }

      existingScript.addEventListener('load', () => resolve(), {once: true});
      existingScript.addEventListener('error', () => reject(new Error('Klee failed to load.')), {once: true});
    });
  }

  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.id = KLEE_SCRIPT_ID;
    script.src = KLEE_SCRIPT_SRC;
    script.async = true;
    script.onload = () => resolve();
    script.onerror = () => reject(new Error('Klee failed to load.'));
    document.body.appendChild(script);
  });
}

export default function KleePlayground(): JSX.Element {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [source, setSource] = useState(exampleBlueprint);
  const [message, setMessage] = useState<string>('Paste copied Blueprint nodes, then press Render Blueprint.');

  async function renderBlueprint() {
    const canvas = canvasRef.current;

    if (!canvas) {
      setMessage('Canvas is not ready yet.');
      return;
    }

    if (!source.trim()) {
      setMessage('Paste copied Blueprint node text first.');
      return;
    }

    try {
      setMessage('Rendering Blueprint...');
      canvas.innerHTML = source;
      canvas.textContent = source;

      await loadKleeScript();

      if (!window.Klee) {
        setMessage('Klee loaded, but the Klee API was not found.');
        return;
      }

      const existingInstance = window.Klee.get?.(canvas);
      const instance = existingInstance ?? window.Klee.init?.(canvas);

      instance?.display?.(source);
      setMessage('Render requested. If the canvas is still blank, Klee could not parse this Blueprint export.');
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error.';
      setMessage(`Klee render failed: ${errorMessage}`);
    }
  }

  function clearSource() {
    setSource('');
    setMessage('Paste copied Blueprint nodes, then press Render Blueprint.');
  }

  return (
    <section className={styles.wrapper}>
      <div className={styles.controls}>
        <button type="button" className="button button--primary" onClick={renderBlueprint}>
          Render Blueprint
        </button>
        <button type="button" className="button button--secondary" onClick={() => setSource(exampleBlueprint)}>
          Load Example
        </button>
        <button type="button" className="button button--secondary" onClick={clearSource}>
          Clear
        </button>
      </div>

      <label className={styles.label} htmlFor="klee-blueprint-source">
        Blueprint Source
      </label>
      <textarea
        id="klee-blueprint-source"
        className={styles.textarea}
        value={source}
        onChange={(event) => setSource(event.target.value)}
        spellCheck={false}
      />

      <p className={styles.message}>{message}</p>

      <div className={styles.canvasFrame}>
        <canvas ref={canvasRef} className="klee" data-klee-paste="true" height={620} />
      </div>
    </section>
  );
}
